### ISSUE TITLE
Pokeplayer pokemon can only use moves when pointed at another mob

### ISSUE THREAD

**Issue by Greenjoe12345** [Pokecube-Development/Pokeplayer#3]
#### Issue Description:
Pokeplayer pokemon can only use moves when pointed at another mob

#### What happens:
When you point at a mob and use a move with alt and click, it works, but if you just try to fire a move such as water gun into the air it will not work

#### What you expected to happen:
to be able to use moves without aiming at a mob

#### Steps to reproduce:

1. become a pokemob
2. use a move such as water gun while not looking at a mob
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.8.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by Thutmose** [comment]
these were all fixed, but the thutcore update seems to have re-broken them, will test some more...
